"""deadline -> finished

Revision ID: 1b8db8759f45
Revises: 6e2e7ae5a49c
Create Date: 2024-11-18 21:13:14.335878

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b8db8759f45"
down_revision: Union[str, None] = "6e2e7ae5a49c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("finished", sa.DateTime(), nullable=True))
    op.drop_column("task", "deadline")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column(
            "deadline", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("task", "finished")
    # ### end Alembic commands ###
